spring:
  #静态资源处理
  resources:
    #启动默认静态资源处理，默认启用
    add-mappings: true
    cache:
      cachecontrol:
        max-age: 3600
    chain:
      #资源链启动缓存，默认启动
      cache: true
      #启动资源链，默认禁用
      enabled: true
      #启动压缩资源（gzip，brotli）解析，默认禁用
      compressed: true
      #启动h5应用缓存，默认禁用
      html-application-cache: true
    static-locations: classpath:/static/

  # thymeleaf配置
  thymeleaf:
    # 默认关闭缓存
    cache: false

  #配置数据源
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seckill?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 1254
    hikari:
      # 连接池名
      pool-name: DateHikaiCP
      #最小空闲连接数
      minimum-idle: 5
      #空闲连接默认存活时间， 默认十分钟
      idle-timeout: 18000
      #最大连接数 默认10
      maximum-pool-size: 10
      #从连接池返回的连接自动提交
      auto-commit: true
      #默认连接超时时间30秒
      max-lifetime: 3000
      #测试连接是否可用的查询语句
      connection-test-query: SELECT 1



  #配置redis数据源
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    timeout: 10000ms
    lettuce:
      pool:
        #最大连接数
        max-active: 8
        #最大连接堵塞等待时间 默认 -1
        max-wait: 10000ms
        #最大连接空闲 默认8
        max-idle: 200
        #最小连接空闲 默认 0
        min-idle: 5



  rabbitmq:
    # 服务器
    host: localhost

    #用户信息
    username: guest
    password: guest
    port: 5672

    listener:
      simple:
        #消费者最小数量
        concurrency: 10
        #消费者最大数量
        max-concurrency: 10
        #限制消费者每次只处理一条消息，处理完再继续下一条消息
        prefetch: 1
        #启动时默认启动容器，默认为true
        auto-startup: true
        #被拒绝时重新进入队列
        default-requeue-rejected: true

    template:
      retry:
        #发布重试，默认false
        enabled: true
        # 重试最大间隔时间默认1000ms
        initial-interval: 1000ms
        #默认最大次数，默认为3次
        max-attempts: 3
        #重试最大间隔时间，默认1000ms
        max-interval: 10000ms
        #重试间隔乘数， 比如2 第一次等10s，第二次等20，
        multiplier: 1
mybatis-plus:
  #配置mapper.xml文件路径
  mapper-locations: classpath:/mapper/*Mapper.xml
  #配置mybatis数据返回的类别名（默认别名是类名）
  type-aliases-package: com.tstar.seckill.pojo


# mybatis SQL打印（方法接口所在的包，不是Mapper.xml所在的包）
logging:
  level:
    com.tstar.seckill.mapper: debug
